### DISCUSSION TITLE
Is it possible to throw Bad Request exception when invalid query string parameter is passed?

### DISCUSSION THREAD

**Discussion by mario-cale** [stoplightio/prism#1832] [Q&A]
Hi everyone,

I plan on using prism mock capabilities to design my APIs in "API first" way.
Plan is to write contract tests against the schema before any development on the server is done and run those tests on mock server generated by prism.
Once the actual server is done, these tests would still work as expected when pointed to the actual server.

So far the plan is going great, but i can't seem to force prism mock server to validate invalid query string parameters.
Path definition:
```
paths:  
  /api/programs:
    get:
      summary: Returns all programs from database with their basic data
      description: 'Sample: GET: /api/programs'
      parameters:
        - $ref: ../components/parameters/program-name.yml#/ProgramName
        - $ref: ../components/parameters/language-iso-code.yml#/LanguageIsoCode
```

Request that should fail:
GET: http://localhost:4010/api/programs?nonExistentParam=randomVal

Is there a way to force the mock server to return Bad Request in this case?

Thanks for the help!
