### DISCUSSION TITLE
How to use x-faker attribute with random.arrayElements

### DISCUSSION THREAD

**Discussion by michaelklopf** [stoplightio/prism#1913] [Q&A]
Hi,

is it possible to use the random.arrayElements function provided by faker?

I'm trying variations of
```yaml
          x-faker: random.arrayElements(['Soup', 'Ice'])
          x-faker: random.arrayElement(['Soup', 'Ice'])
          x-faker: random.arrayElements.bind(null, ['Soup', 'Ice'])
```

but I don't get any of the array elements in the response for that attribute. Is it possible at all, am I using the wrong syntax?
