### DISCUSSION TITLE
Use Prism in Bitbucket pipelines for integration test

### DISCUSSION THREAD

**Discussion by tonybentley** [stoplightio/prism#2158] [Q&A]
I would like to use Prism as a service mock in Bitbucket pipelines, but have not been successful.

docker-compose:
```
services:
apimock:
    # Locking to 4.10.3 due to open issue in prism with 4.10.4 - https://github.com/stoplightio/prism/issues/2138
    image: stoplight/prism:4.10.3
    platform: linux/amd64
    command: 'mock -h 0.0.0.0 /tmp/api.json'
    volumes: 
      - ./docker/apiv2mock/api.json:/tmp/api.json:ro
    ports:
      # Serve mocked API locally on port 8999
      - '8999:4010'
```
I have tried using script and running various commands in bitbucket-pipelines.yml:

```
  services:
    apiv2mock:
      image: stoplight/prism:4.10.3
      platform: linux/amd64
      ports:
        - '8999:4010'
      volumes: 
        - ${$BITBUCKET_CLONE_DIR}/docker/apimock/api.json:/tmp/api.json:ro
      script: 
        - mock -h 0.0.0.0 /tmp/api.json
```

No success with several iterations of volumes and script. The result is always:

```
prism <command>
Commands:
  prism mock <document>              Start a mock server with the given document file
  prism proxy <document> <upstream>  Start a proxy server with the given document file
Options:
  --version  Show version number  [boolean]
  --help     Show help  [boolean]

```

Which seems to indicate that it's using the default ENTRYPOINT of `prism`.
