### DISCUSSION TITLE
Make a dynamic response generation based on multiple the examples (OpenAPI 3.1)

### DISCUSSION THREAD

**Discussion by oliviernguyenquoc** [stoplightio/prism#2335] [Ideas]
It would be great not to have to use Faker to have a dynamic response generation.
It would be better to fully based the generation on the multiple examples we can provide in OpenAPI 3.1

```YAML
examples:
    cat:
      summary: An example of a cat
      value:
        name: Fluffy
        petType: Cat
        color: White
        gender: male
        breed: Persian
    dog:
      summary: An example of a dog with a cat's name
      value:
        name: Puma
        petType: Dog
        color: Black
        gender: Female
        breed: Mixed
```

We could imagine that response generated would be a combination of fields coming from examples.
In the example above, response generated could be:

```json
{
  "name": "Puma",
  "petTupe": "Cat",
  "color": "White",
  "gender": "Female",
  "breed": "Mixed",
}
```
