### ISSUE TITLE
Prism listens correctly with -h 0.0.0.0 when accessed from browser but not from another docker container 

### ISSUE THREAD

**Issue by VenkatRamReddyK** [stoplightio/prism#1010]
**Describe the bug**

 Prism when running with `-h 0.0.0.0` in a docker container responds as expected when we run `http://0.0.0.0:4010/api/users` in the chrome browser. 
But, when we execture `wget -O/dev/null http://0.0.0.0:4010/api/users` in another docker container it doesn't listen on `0.0.0.0:4010`.

**To Reproduce**

 **Dockerfile for Prism** 

**Build**: `docker build -t mock/prism-server .` 
**Run**: `docker run -p 4010:4010 mock/prism-server:latest`

**Dockerfile**

```
FROM node:10

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4010

CMD ["npm", "run", "prism"]
  
```

**package.json**

```
{
  "name": "prism-mock-server",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@stoplight/prism-cli": "3.2.9"   
  },
  "scripts": {
    "prism": "prism mock masterSpec.inc.yaml -h 0.0.0.0 --dynamic"
  }
}
```

**Docker Image for Running tests** 

**Build**: `docker build -t tests .`
**Run** : `docker run -p 4011:41 run-tests:latest`

**Dockerfile**

```
FROM bash

WORKDIR /usr/src/

COPY run-test.sh ./

CMD ["./run-test.sh"]

```

**Sample code for checking prism is up**. run-test.sh

```
while true
do
  echo "Checking if Prism mock server is up... "
  wget -O/dev/null http://0.0.0.0:4010/api/users > /dev/null 2>&1
  status=$?
  echo "Prism Status: $status"
  if [ $status -eq 0 ]; then
    echo "Prism mock server is up now. "
    break
  fi
done


```

**Expected behavior**
 http://0.0.0.0:4010/api/users  should be able to access in another docker container.

**Environment (remove any that are not applicable):**
 - Prism 3.2.9
 - OS: Mohave
 - Browser: chrome
 - Docker version 19.03.5

**Additional context**
I tried to bind the docker containers using docker-compose.yml as well but the result is same.

**docker-compose.yml**

```
version: "3"
services:
  tests:
    container_name: run-tests
    build: ./run-tests
    depends_on:
      - prism  
  prism:
    container_name: prism
    build: ./prism
    image: prism
    restart: always    
    expose:
      - "4010"    
    ports:
      - "4010:4010"  
```

**Logs** 

**Logs for checking prism is up** for Dockerfile that runs  run-test.sh

Checking if Prism mock server is up... retry number: 1
Prism Status: 1
Checking if Prism mock server is up... retry number: 2
Prism Status: 1
Checking if Prism mock server is up... retry number: 3
Prism Status: 1
Checking if Prism mock server is up... retry number: 4
Prism Status: 1
Checking if Prism mock server is up... retry number: 5
Prism Status: 1
