### ISSUE TITLE
Validation should error on additional properties

### ISSUE THREAD

**Issue by Lakitna** [stoplightio/prism#1157]
**User story.**

As a tester, I can make sure that my OAS aligns with our implementation so that I can use the OAS as a contract.

**Is your feature request related to a problem?**

When I'm testing an API I have to make sure that it has been implemented according to the specifications. This includes things like missing required fields for which the validator proxy is great. However, I also want to know when unspecified properties are present. These additional properties are often typos or a leak of internal code and it increases the payload size unnecessarily.

**Describe the solution you'd like**

Given the (partial) OAS

```yaml
type: object
properties:
  foo:
    type: string
```

And this response

```json
{
  "foo": "some string",
  "bar": 123
}
```

It should throw an error because `bar` is an unspecified property.

**Additional context**

This is a must-have feature when you're workflow is to first define the interface by writing the OAS and then implement it based on those specifications.

**Comment by pytlesk4** [comment]
@Lakitna this should already be supported, just need to add `additionalProperties: false`.

```yaml
type: object
additionalProperties: false
properties:
  foo:
    type: string
```

Give that a spin. Re open the issue if it doesn't work.
