### ISSUE TITLE
204 (NoContent) response throws Unexpected end of JSON input in prism

### ISSUE THREAD

**Issue by ujlbu4** [stoplightio/prism#1361]
## Describe the bug

When I make DELETE request to prism in proxy-mode and downstream responses with 204 (No Content) response , the prism throw error:
```
[3:41:42 PM] › [HTTP SERVER] delete /drivers/1/documents/xyz ✖  error     Request terminated with error: FetchError: invalid json response body at http://localhost:1337/drivers/1/documents/xyz reason: Unexpected end of JSON input
```

## To Reproduce

1. Given this OpenAPI document '...'

```yaml
openapi: 3.0.1
...
'/drivers/{id}/documents/{documentId}':
    delete:
      deprecated: false
      description: Some desc
      operationId: DeleteDriverDocument
      responses:
        '204':
          description: No Content
```

2. Run this CLI command '....'

```bash
$ prism proxy --port 4011 specs/openapi.yaml http://localhost:1337
```

3. See error

Returned response:
```
Response:
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Headers: *
  Access-Control-Allow-Credentials: true
  Access-Control-Expose-Headers: *
  Date: Mon, 24 Aug 2020 16:41:42 GMT
  Connection: keep-alive
  Content-Type: application/problem+json
  Content-Length: 209
}
DEBUG: response body: {"type":"FetchError","title":"invalid json response body at http://localhost:1337/drivers/1/documents/xyz reason: Unexpected end of JSON input","status":500,"detail":""}
```

prism output:
```
[3:41:42 PM] › [HTTP SERVER] delete /drivers/1/documents/xyz ✖  error     Request terminated with error: FetchError: invalid json response body at http://localhost:1337/drivers/1/documents/xyz reason: Unexpected end of JSON input
```

If i make request directly to downstream (without proxy) the response is next one:
```
Response:
StatusCode: 204, ReasonPhrase: 'xxx', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Mon, 24 Aug 2020 16:59:08 GMT
  Server: Kestrel
  Set-Cookie: ss-id=Hj2sXJpZD6JfbBk6Mhtg; path=/; httponly
  Set-Cookie: ss-pid=WzG6jXa0ZdCNLSaPeGsB; expires=Fri, 24 Aug 2040 16:59:08 GMT; path=/; httponly
  Set-Cookie: ss-opt=temp; expires=Fri, 24 Aug 2040 16:59:08 GMT; path=/; httponly
  Set-Cookie: X-UAId=1; expires=Fri, 24 Aug 2040 16:59:08 GMT; path=/; httponly
  Vary: Accept
  X-Powered-By: ServiceStack/5.70 NetCore/OSX
  Content-Type: text/html
}

```

## Expected behavior

I expect (in priority order) that
1.  prism will successfully process 204 (Not Content) bodies
2. prism will not intervene to response body from downstream
3. even prism failed to parse response, put their errors to special header (not to body)

## Additional context

I would like to show more logs to reproduce, but this issue https://github.com/stoplightio/prism/issues/773 is on hold :( 

**Screenshots**
Not applicable

**Environment (remove any that are not applicable):**
 - Library version: `3.3.4`
 - OS: `macOs`
