### ISSUE TITLE
Faker properties are not respected if one of the type is null

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/prism#1880]
## Describe the bug

When defining properties that are nullable, faker properties are not respected for dynamic responses

## To Reproduce

1. Given this JSON Schema
```
{
  "title": "User",
  "description": "",
  "additionalProperties": false,
  "properties": {
    "email-nonnull": {
      "type": "string",
      "format": "email",
      "x-faker": "internet.email"
    },
    "email-ui": {
      "anyOf": [
        {
          "type": "string",
          "format": "email",
          "x-faker": "internet.email"
        },
        {
          "type": "null"
        }
      ]
    },
    "email-manual": {
      "x-faker": "internet.email",
      "type": [
        "null",
        "string"
      ],
      "format": "email"
    }
  }
}
```
Type with null is not mocked correctly:

![Screenshot 2021-09-02 at 9 40 31 AM](https://user-images.githubusercontent.com/17899454/131782831-71cbd84f-8c91-4b9a-b390-f4f07f2bbd29.png)

This works fine here:
https://json-schema-faker.js.org/

## Expected behavior

Faker properties to be respected

## Additional context
Using hosted prism on Stoplight

**Comment by chohmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Platinum-Falcons-5eb9bc4a1fddfe30b94f78b1/issues/stoplightio/prism/1880?planning-poker) with ZenHub @Amjcraft @lukasz-kuzynski-11sigma @radzserg @rainum

**Comment by lukasz-kuzynski-11sigma** [comment]
Isn't that related to? https://github.com/stoplightio/prism/pull/1899

**Comment by Brett-Best** [comment]
I just tested this again, it looks like the emails now use faker but another issue seems to be introduced which is faker will never generate `null` value for `email-ui` and ` email-manual`.
```shell
curl -H 'authorization: Bearer LOL' -H 'Prefer: dynamic=true' https://stoplight.io/mocks/interact-technology/stoplight-support/11666505/users
```

```yaml
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      properties:
        email:
          type:
            - string
            - 'null'
        email-nonnull:
          type: string
          format: email
          x-faker: internet.email
        email-ui:
          type: string
          format: email
          x-faker: internet.email
          nullable: true
        email-manual:
          type:
            - string
            - 'null'
          format: email
          x-faker: internet.email
```
