### ISSUE TITLE
Generated paths with parameters do not keep in mind the 'style' and 'exploded' properties

### ISSUE THREAD

**Issue by tommie822** [stoplightio/prism#2005]
## Describe the bug

Generating a query path from an OAS3 file does not keep in mind the ability to explode an object into a different query format as is described in the Open Api Specification 3

## To Reproduce

1. Given [this](https://gist.githubusercontent.com/tommie822/a2f055edac4928743108a3d488fc7761/raw/2db47051ea21b6fbcc4dd89dfb8e74b24cb04791/oas3.yml) OpenAPI document
``` yml
openapi: "3.0.2"
info:
  title: Test
  version: "1.0.0"
servers:
  - url: https://api.server.test/v1
paths:
  /recipes:
    get:
      parameters:
        - $ref: "#/components/parameters/Pagination"
      responses:
        "200":
          description: OK
components:
  parameters:
    Pagination:
      name: pagination
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: object
        properties:
          offset:
            type: integer
            example: 0
          limit:
            type: integer
            example: 25
```

3. Run this CLI command `docker run -p 4010:4010  --rm stoplight/prism:4 mock -h 0.0.0.0 https://gist.githubusercontent.com/tommie822/a2f055edac4928743108a3d488fc7761/raw/2db47051ea21b6fbcc4dd89dfb8e74b24cb04791/oas3.yml`
The path created directly uses the parameter object instead of using the properties 'style and explode' to determine the path. See screenshot.
> [11:30:58 AM] › [CLI] ℹ  info      GET        http://0.0.0.0:4010/recipes?pagination=%5Bobject%20Object%5D

## Expected behavior
According to [specification](https://swagger.io/specification/#parameter-object) a parameter object such as
``` yml
    Pagination:
      name: pagination
      in: query
      required: true
      style: form
      explode: true
      schema:
        type: object
        properties:
          offset:
            type: integer
            example: 0
          limit:
            type: integer
            example: 25
```
should result in http://0.0.0.0:4010/recipes?offset=0&limit=25 see screenshot

The code should probably be placed [here](https://github.com/stoplightio/prism/blob/406d659410b02a07a708db19d2a9b4c4febee167/packages/cli/src/util/paths.ts#L142)

**Screenshots**
![image](https://user-images.githubusercontent.com/23521105/157434173-aecdf751-e354-4e9f-b008-6f0ca9a2f4dc.png)
