### ISSUE TITLE
Docker Hub Images with graceful shutdown

### ISSUE THREAD

**Issue by vanam** [stoplightio/prism#2156]
A [prism docker image](https://hub.docker.com/r/stoplight/prism) does not correctly handle `SIGTERM` and `SIGKILL` signals.

## Current Behavior
Following [your documentation](https://meta.stoplight.io/docs/prism/4bf78efbf9dd2-serving-multiple-open-api-documents) i start a container with prism
```
version: '3'
services:
  prism_1:
    image: stoplight/prism
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml
```
When I press <kbd>CTRL</kbd>+<kbd>C</kbd> it sends `SIGTERM` signal (which is ignored) and after default 10s timeout container is stopped.

## Expected Behavior
When I press <kbd>CTRL</kbd>+<kbd>C</kbd> it sends `SIGTERM` signal container should stop immediately.

## Possible Solution(s)
Use [dumb-init](https://github.com/Yelp/dumb-init) or alternatives to gracefully shut down prism as recommended in [10 best practices to containerize Node.js web applications with Docker](https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/#Safely-terminate-Node.js-Docker-web-applications)

```dockerfile
FROM node:16.17.0-bullseye-slim as build
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates wget
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64

FROM stoplight/prism
COPY --from=build /usr/local/bin/dumb-init /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/prism
ENTRYPOINT ["/usr/local/bin/dumb-init", "--", "/usr/local/bin/prism"]

```

PS: On your [Docker Hub](https://hub.docker.com/r/stoplight/prism) and here in this repo I was unable to find Dockerfiles which were used to generate Docker Hub's images. I would love to see "Supported tags and respective Dockerfile links" like eg. [MySQL](https://hub.docker.com/_/mysql) has. That would make debugging and possibly fixing this issue much easier.
