### ISSUE TITLE
Mocked arrays always have max number of items

### ISSUE THREAD

**Issue by stojsavljevic** [stoplightio/prism#2206]
When mocking an API, I would like get arrays of random size.

I'm using latest docker Prism image in dynamic mode. My OpenAPI resource field is defined like this:
```
components:
  schemas:
    Location:
      ...
      properties:
        ...
        testProp:
          type: array
          uniqueItems: true
          minItems: 0
          maxItems: 3
          items:
            type: string
            enum:
              - A
              - B
              - C
          example:
            - A
            - C
```
in this case I **always** get response with 3 items. I get this:
```
      "testProp":[
         "A",
         "B",
         "C"
      ]
```

Is it possible to get this field with random size (0-3 in my case)?
