### ISSUE TITLE
Prism doesn't mock enums 

### ISSUE THREAD

**Issue by DannyCork** [stoplightio/prism#225]
Hi,
I am using prism to mock a swagger yml file like so:

```
$ prism mock --spec swagger.yml
Prism version is 2.0.17
Prism mock server started on port 4010
```

The yml file contains an enum as depicted below:

  ```
  region:
                    type: "string"
                    enum:
                      - "a1"
                      - "a2"
                      - "a3"
                      - "a4"
                      - "a5"
                      - "a6"
                      - "a7"
```

When I make a request to the mocked prism server , I note that the response contains the region field however it is not an enum:

```
"region": "incididunt laborum ad in",
or 
"region": "officia"
or 
"region": "voluptate",

etc....
```

Is this observation correct? Does Prism not generate enums from the swagger definition file?

thanks in advance.
Danny.
