### ISSUE TITLE
Allow specifying format of dynamic property keys using x-factor attributes

### ISSUE THREAD

**Issue by keyboSlice** [stoplightio/prism#2287]
## Context

It would be useful to be able to enforce consistency of dynamic properties defined in the schema using `additionalProperties` through the use of an x-faker attribute.

For example:

```yaml
additionalProperties:
  type: array
  x-key-faker: word.noun
  items:
    type: string
```

## Current Behavior

Property keys defined in `additionalProperties` are completely randomised.

## Expected Behavior

Dynamic property keys would be created using the defined faker method
