### ISSUE TITLE
Prism misvalidate boolean query params

### ISSUE THREAD

**Issue by welcoMattic** [stoplightio/prism#2452]
## Context
It fails request against our Prism mock server during Functional test suite running.

## Current Behavior
Considering the following OpenAPI spec:

```yaml
paths:
  /api/endpoint:
    post:
      // …
      parameters:
        - name: fooBoolParam
          in: query
          required: false
          schema:
            type: boolean
            default: true
```

Calling a URL like `/api/endpoint?fooBoolParam=1` leads to a Prism failure

```
[5:34:16 PM] › [HTTP SERVER] post /api/endpoint ℹ  info      Request received
[5:34:16 PM] ›     [NEGOTIATOR] ℹ  info      Request contains an accept header: application/json
[5:34:16 PM] ›     [VALIDATOR] ⚠  warning   Request did not pass the validation rules
[5:34:16 PM] ›     [VALIDATOR] ✖  error     Request query parameter fooboolparam must be boolean
[5:34:16 PM] ›     [NEGOTIATOR] ✔  success   Found response 400. I'll try with it.
[5:34:16 PM] ›     [NEGOTIATOR] ✔  success   The response 400 has an example. I'll keep going with this one
[5:34:16 PM] ›     [NEGOTIATOR] ℹ  info      Adding "Deprecation" header since operation is deprecated
[5:34:16 PM] ›     [NEGOTIATOR] ✔  success   Responding with the requested status code 400
[5:34:16 PM] ›     [NEGOTIATOR] ℹ  info      > Responding with "400"
[5:34:16 PM] ›     [VALIDATOR] ✖  error     Violation: request.query.fooboolparam Request query parameter fooboolparam must be boolean
```

## Expected Behavior
Prism should validate boolean like format in query string like `0` or `1`.

## Possible Workaround/Solution
Nothing, I had to change the type of my parameter in the OpenAPI spec to `mixed` to bypass this bug.

## Steps to Reproduce

1. Run Prism with the small extract of OpenAPI spec previously provided
2. Call the URL
3. Enjoy the error

## Environment

- Version used: 4.10.3 (tested also in 5.5.3)
