### ISSUE TITLE
Stoplight ignores pattern - why?

### ISSUE THREAD

**Issue by WilliamDEdwards** [stoplightio/prism#2698]
Property in spec:
```
team_code:
  type: string
  maxLength: 6
  minLength: 4
  pattern: ^[A-Z0-9]+$
  title: Team Code
```

Generated value by Stoplight:

    string

This is not a valid value according to the specified pattern.

Why is Stoplight ignoring the pattern?

--

Running Stoplight 5.14.2 with:

    [ "mock", "-h", "0.0.0.0", "openapi.json" ]
