### ISSUE TITLE
Test Harness: Dynamic XML Responses

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#415]
**User Story**

As a Prism user, I can request a dynamic XML response, so that I don't have to add static examples to a spec.

Note this feature is currently not implemented so expect tests to fail 

When dealing with OAS3 refer to this doc: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#xml-object

One example of more advanced use case is for instance:
```
Person:
  type: object
  properties:
    id:
      type: integer
      format: int32
      xml:
        attribute: true
    name:
      type: string
      xml:
        namespace: http://example.com/schema/sample
        prefix: sample
```
converts to:
```
<Person id="123">
    <sample:name xmlns:sample="http://example.com/schema/sample">example</sample:name>
</Person>
```
But honestly just check out the documentation, it has plenty of simple and advanced use cases  

**ACs**
- add test cases to test harness
- add at least the cases described in the examples section
- if any of the test fails then mark that it is an invalid result (e.g. mark as skipped) and report a Jira bug
- link that bug to this card
- Make sure to add the actual tests to TestRails

**Additional resources**

https://stoplightio.atlassian.net/wiki/spaces/EN/pages/52887637/Prism#Prism-MockServerFeatures (please find relevant row)

**Test examples**

Given there are no examples defined for an operationAnd this operation can produce application/xml responseAnd that operation's response schema has XML propertyAnd I make a request to this operationAnd the request has Accept header of application/xmlThen I should get a response with dynamically generated XML as payload

Given there are examples defined for an operationAnd this operation can produce application/xml responseAnd that operation's response schema has XML propertyAnd I make a request to this operationAnd the request has Accept header of application/xmlAnd I add __dynamic=true to the query pathThen I should get a response with dynamically generated XML as payload

Given there is a dynamic XML response generated for an operationAnd the operation has headers definedWhen I make a request to this operationThen I should get back a XML response having these headers generated and included in the response
