### ISSUE TITLE
Prism doesn't handle nullable fields properly in mocked responses

### ISSUE THREAD

**Issue by LesterTheTester** [stoplightio/prism#486]
When I specify nullable fields in a OAS3 file, I expect prism to be able to return null values in mocks for these fields. Example spec:

```
components:
  schemas:
    Pagination:
      description: "Defines an object containing information for cursor based pagination."
      type: object
      properties:
        ending_before:
          type: string
          nullable: true
          default: null
        starting_after:
          type: string
          nullable: true
          default: null
```

Prism output: 

`pagination: {
ending_before: "",
starting_after: "",
`

Note prism is sending empty strings, not nulls. SwaggerUI seems to be handling this OK, however, so I'm pretty sure our spec is OK:

![Screen Shot 2019-07-23 at 6 29 12 AM](https://user-images.githubusercontent.com/4722184/61741120-0cc38680-ad45-11e9-8b02-0977635bb45f.png)
