### ISSUE TITLE
support for `writeOnly` schema property

### ISSUE THREAD

**Issue by equalspeterd** [stoplightio/prism#524]
**User story.**
As a schema designer, I want to use the openAPI `writeOnly` property to control schema request/response behavior.

**Describe the solution you'd like**
support:
```
schemas:
    secretType:
          properties:
            x:
              type: string
              description: present/allowed in read and write operations (GET, POST, PUT)
            y:
              writeOnly: true
              description: allowed for PUT/POST, not included in GET responses (for example)
```
