### ISSUE TITLE
Empty responses are not supported for 401's due to failed security scheme

### ISSUE THREAD

**Issue by LesterTheTester** [stoplightio/prism#592]
The [openAPI](https://swagger.io/docs/specification/describing-responses/) spec says that I can specify a response without a body by not providing `content:` or `schema:`. However, if one of these is not present, the errors generated by the new securitySchema check will not be used, and prism will use it's default response.

**To Reproduce**

1.  Have a response defined like this attached to an endpoint as a 401

```
InvalidAuthorizationTokenResponse:
      description: "The provided authorization token is invalid or expired."
```

```
responses:
        200:
          $ref: '#/components/responses/SuccessfulUserResponse'
        401:
          $ref: '#/components/responses/InvalidAuthorizationTokenResponse'
```

and a security scheme like:
```
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

2. Hit the endpoint without an authorization token
3. The default error message is sent since the 401 has no schema or example:

```
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

**Expected behavior**
I'd like to have my custom, bodyless 401 returned.
