### ISSUE TITLE
Cannot get Prism to bind to IP when running in Kubernetes

### ISSUE THREAD

**Issue by dijitali** [stoplightio/prism#857]
## Describe the bug

I am trying to run Prism within Kubernetes behind an Ingress but am having trouble getting Prism to bind to an IP.

If I don't specify a host, at all I am unable to connect to the Prism pod (expected, since Prism's default value is the loopback address `127.0.0.1`).

But if I specify a [wildcard mask](https://en.wikipedia.org/wiki/Wildcard_mask) via: `-h 0.0.0.0` (as recommended by #634), I get the following error on startup:

```text
[CLI] …  awaiting  Starting Prism…
[CLI] ✖  fatal     getaddrinfo ENOTFOUND  "0.0.0.0"
```

If I specify the k8s pod's IP address [via the Kubernetes downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables), I get a similar error:

```text
[CLI] …  awaiting  Starting Prism…
[CLI] ✖  fatal     getaddrinfo ENOTFOUND  <my prism pod ip>
```

## To Reproduce

1. Given these Kubernetes manifests for a deployment and service running Prism:

        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: prism-openapi-mocks
          namespace: api-mocks
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: prism
              app.kubernetes.io/part-of: openapi-mocks
          template:
            metadata:
              labels:
                app.kubernetes.io/name: prism
                app.kubernetes.io/part-of: openapi-mocks
            spec:
              volumes:
                - name: swagger-spec
                  configMap:
                    name: swagger-spec
                    items:
                      - key: swagger-spec.yaml
                        path: swagger-spec.yaml
              containers:
                - name: prism
                  image: stoplight/prism:3
                  volumeMounts:
                    - name: swagger-spec
                      mountPath: /etc/config
                  env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                          fieldPath: status.podIP
                  args:
                    - mock
                    #- -h $(MY_POD_IP) <THIS DOESN'T WORK>
                    - "/etc/config/swagger-spec.yaml"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: prism-openapi-mocks
          namespace: api-mocks
        spec:
          type: ClusterIP
          ports:
            - name: http
              protocol: TCP
              port: 80
              targetPort: 4010
          selector:
            app.kubernetes.io/name: prism
            app.kubernetes.io/part-of: openapi-mocks

1. Observe that the Prism pod will refuse connections from other pods:

```shell
# Launch a pod with curl
kubectl run -i --tty --rm debug --image=curlimages/curl --restart=Never -- sh

# Attempt to connect to the Kubernetes Service
/ $ curl prism-openapi-mocks.api-mocks.svc.cluster.local
curl: (7) Failed to connect to prism-openapi-mocks.api-mocks.svc.cluster.local port 80: Connection refused

# Attempt to connect to the pod directly
/ $ curl <my prism pod ip>:4010
curl: (7) Failed to connect to <my prism pod ip> port 4010: Connection refused
```

## Expected behavior

I expect Prism to bind to all network interfaces by default.

## Environment:

- Library version: Prism docker image tag [3](https://hub.docker.com/layers/stoplight/prism/3/images/sha256-ffcee64a1c8ef46cd3059811aa1341993e43df34548522c66cd553da095c5d3c) (have also tried [2](https://hub.docker.com/layers/stoplight/prism/2/images/sha256-c3881006cf237bb811791c0e29ff4bfbedb14b5f452fb9e36eca6d00e9ae55a3))
- OS: [GKE CoS](https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#container-optimized_os) v1.13.11-gke.14

**Comment by dijitali** [comment]
For comparison, the same process using the [example NGINX deployment](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/#creating-and-exploring-an-nginx-deployment) works fine (I can get the default NGINX page back from curl) and we also run a large number of other Node.js containers in this same cluster, perhaps indicating the IP binding issue is specific to Prism.

**Comment by XVincentX** [comment]
I have no problems running Prism's CLI in Kubernetes (Deployment + Service).

This image is coming from a Kubernetes Cluster using Rancher:

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/1416224/69653224-29652780-1073-11ea-96cd-214f701f580b.png">

**Comment by dijitali** [comment]
@XVincentX - thanks for taking the time to confirm.

After many, many hours of googling, searching fastify docs and troubleshooting NetworkPolicies, the issue was similar to [this StackOverflow post](https://stackoverflow.com/questions/50784868/running-json-server-in-docker).

Specifically it was the parameters in the deployment spec.  Instead of:

```yaml
          args:
            - mock
            - -h "0.0.0.0"
            - "/etc/config/swagger-spec.yaml"
```

It needs to be:
```yaml
          args:
            - mock
            - -h 
            - "0.0.0.0"
            - "/etc/config/swagger-spec.yaml"
```

I didn't spot it because Prism was returning the correct value in the error log but apparently it parsed the argument differently.

Just my opinion: but I feel it would be a bit more user friendly and follow [POLA](https://www.ibm.com/developerworks/web/library/us-cranky10/index.html) if Prism left the default Fastify behaviour unchanged and bound to `0.0.0.0` by default instead of only the loopback.

**Comment by thiDucTran** [comment]
figures i post to offer quick copy-paste help..i am also using `kustomize`

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism-openapi-mocks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prism
      app.kubernetes.io/part-of: openapi-mocks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prism
        app.kubernetes.io/part-of: openapi-mocks
    spec:
      volumes:
        - name: petstore-oas3
          configMap:
            name: petstore-oas3
            items:
              - key: petstore-oas3.yaml
                path: petstore-oas3.yaml
      containers:
        - name: prism
          image: prism
          volumeMounts:
            - name: petstore-oas3
              mountPath: /etc/config
          args:
            - mock
            - -h
            - "0.0.0.0"
            - "/etc/config/petstore-oas3.yaml"
```

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omatic

images:
- name: prism
  newName: omacrrdcontainerregistry.azurecr.io/prism
  newTag: '5.5.1'

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: petstore-oas3
  files:
  - petstore-oas3.yaml=petstore-oas3.yaml
```

`service.yaml`
```yaml
 apiVersion: v1
 kind: Service
 metadata:
   name: prism-openapi-mocks
 spec:
   type: ClusterIP
   ports:
     - name: http
       protocol: TCP
       port: 80
       targetPort: 4010
   selector:
     app.kubernetes.io/name: prism
     app.kubernetes.io/part-of: openapi-mocks
```

`petstore-oas3.yaml`h - see [here](https://github.com/stoplightio/prism/blob/master/examples/petstore.oas3.yaml)

**Comment by thiDucTran** [comment]
figures i post to offer quick copy-paste help..i am also using `kustomize`

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism-openapi-mocks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prism
      app.kubernetes.io/part-of: openapi-mocks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prism
        app.kubernetes.io/part-of: openapi-mocks
    spec:
      volumes:
        - name: petstore-oas3
          configMap:
            name: petstore-oas3
            items:
              - key: petstore-oas3.yaml
                path: petstore-oas3.yaml
      containers:
        - name: prism
          image: prism
          volumeMounts:
            - name: petstore-oas3
              mountPath: /etc/config
          args:
            - mock
            - -h
            - "0.0.0.0"
            - "/etc/config/petstore-oas3.yaml"
```

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: valueHere

images:
- name: prism
  newName: registryPath/prism
  newTag: '5.5.1'

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: petstore-oas3
  files:
  - petstore-oas3.yaml=petstore-oas3.yaml
```

`service.yaml`
```yaml
 apiVersion: v1
 kind: Service
 metadata:
   name: prism-openapi-mocks
 spec:
   type: ClusterIP
   ports:
     - name: http
       protocol: TCP
       port: 80
       targetPort: 4010
   selector:
     app.kubernetes.io/name: prism
     app.kubernetes.io/part-of: openapi-mocks
```

`petstore-oas3.yaml` - see [here](https://github.com/stoplightio/prism/blob/master/examples/petstore.oas3.yaml)
